# Use a lightweight Node.js image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

RUN npm install -D tailwindcss postcss autoprefixer && npx tailwindcss init && npm install react-router-dom && npm install axios && npm i react-markdown@8.0.6

# Expose Vite's default port
EXPOSE 5173

# Command to start the Vite development server
CMD ["npm", "run", "dev", "--", "--host"]
